FROM alpine:latest

ARG TARGETPLATFORM

ENV TZ=Asia/Shanghai

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/autofilm /usr/local/bin/autofilm

VOLUME ["/config", "/logs", "/media", "/fonts"]
WORKDIR /

ENTRYPOINT ["/usr/local/bin/autofilm"]
