name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-binary:
    uses: ./.github/workflows/build-binary.yaml

  build-docker:
    needs: build-binary
    uses: ./.github/workflows/build-docker.yaml
    with:
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  github-release:
    name: Create GitHub Release
    needs: [build-binary, build-docker]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Download release artifact
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          files: |
            AutoFilm*
            LICENSE
            config/config.example.yaml
            README.md
