name: rustfmt-check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  fmt-check:
    name: Rust Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust Format Check
        run: cargo fmt --check
